name: CI/CD Pipeline - ProfessorXTrader

on:
  push:
    branches: [ main, develop, feature/*, fix/* ]
  pull_request:

jobs:
  test:
    name: test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.17.0, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    # URGENT FIX: Use .nvmrc file for Node version
    - name: Setup Node.js (with cache)
      if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json','**/yarn.lock') != '' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: package-lock.json
    
    - name: Setup Node.js (no cache)
      if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json','**/yarn.lock') == '' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    
    # URGENT FIX: Removed continue-on-error for critical build/test steps
    - name: Install deps + project setup
      run: |
        if [ -f package-lock.json ]; then npm ci; else npm install; fi
        npm run ai-setup
    
    - name: Typecheck
      run: npm run type-check --if-present
    
    - name: Lint
      run: npm run lint --if-present
    
    - name: Tests
      run: |
        npm run test-api --if-present
        npm run indicators-test --if-present
        npm run test-ai-api --if-present
      env:
        BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
        BINANCE_SECRET_KEY: ${{ secrets.BINANCE_SECRET_KEY }}
        BINANCE_TESTNET: true
        ENABLE_AI_FEATURES: true
        TENSORFLOW_BACKEND: cpu
    
    - name: Build
      run: npm run build --if-present
      env:
        ENABLE_AI_FEATURES: true
        TENSORFLOW_BACKEND: cpu
    
    # CONTINUE-ON-ERROR only for uploads/artifacts
    - name: Upload coverage reports
      if: always()
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.node-version }}
        path: coverage/
        retention-days: 7
    
    - name: Upload build artifacts
      if: always() 
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.node-version }}
        path: .next/
        retention-days: 3

  deploy:
    name: deploy
    needs: test
    if: github.ref == 'refs/heads/main' && needs.test.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: package-lock.json
    
    - name: Install + Build
      run: |
        npm ci || npm install
        npm run build
      env:
        ENABLE_AI_FEATURES: true
        TENSORFLOW_BACKEND: cpu
    
    - name: Deploy to Vercel
      continue-on-error: true
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: .
        prod: true
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}